#! /usr/bin/bash
gcc -c engine.c
ar -rc libengine.a engine.o
ranlib libengine.a
gcc main.c -o a.out -g -fexpensive-optimizations -flto -O -Wunreachable-code -Wno-deprecated -Wno-unknown-pragmas -DUNICODE -L. -lengine -lm `sdl2-config --cflags --libs`
